[build]
  command = "npm run build && netlify-lambda build src/functions"
  publish = "build"
  functions = "build/lambda/"


  

[[redirects]]
  from = "/getvideos"
  to="https://naughty-minsky-7ba47b.netlify.app/.netlify/functions/getvideos"
  status = 200