[build]
  publish = "videos-hooks-w-netlify-serverless-function-TEST/build/"
  functions = "videos-hooks-w-netlify-serverless-function-TEST/src/lambda/"
  base = "videos-hooks-w-netlify-serverless-function-TEST/"

  

[[redirects]]
  from = "/getvideos"
  to="https://naughty-minsky-7ba47b.netlify.app/.netlify/functions/getvideos"
  status = 200