[build]
  publish = "build/"
  functions = "build/lambda/"
  base = "build/"

  

[[redirects]]
  from = "/getvideos"
  to="https://naughty-minsky-7ba47b.netlify.app/.netlify/functions/getvideos"
  status = 200